<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\common.props" />
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <Configurations>Debug;Release;CI</Configurations>
        <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
        <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>
        <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
        <GenerateAssemblyFileVersionAttribute>true</GenerateAssemblyFileVersionAttribute>
        <LangVersion>default</LangVersion>
        <Platforms>AnyCPU</Platforms>
        <TargetFrameworks>net10.0;net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'CI' ">
      <Optimize Condition=" '$(Optimize)' == '' ">true</Optimize>
      <NoWarn>1701;1702;0618;xUnit1051;xUnit1031</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <NoWarn>1701;1702;0618;xUnit1051;xUnit1031</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <NoWarn>1701;1702;0618;xUnit1051;xUnit1031</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="App.config" />
        <PackageReference Include="FluentAssertions" Version="5.10.3" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="Microsoft.Reactive.Testing" Version="5.0.0" />
        <PackageReference Include="Moq" Version="4.20.69" />
        <PackageReference Include="Moq.AutoMock" Version="3.5.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="System.Linq.Async" Version="7.0.0" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.0'">
        <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
        <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
        <PackageReference Include="System.Net.Security" Version="4.3.2" />
        <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
        <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
        <PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
        <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    </ItemGroup>
    <ItemGroup>
        <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Neo4j.Driver.Reactive\Neo4j.Driver.Reactive.csproj" />
      <ProjectReference Include="..\Neo4j.Driver.Tests.SimpleDriver\Neo4j.Driver.Tests.SimpleDriver.csproj" />
      <ProjectReference Include="..\Neo4j.Driver\Neo4j.Driver.csproj" />
    </ItemGroup>
</Project>
