<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\common.props" />
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Configurations>Debug;Release;CI</Configurations>
        <Platforms>AnyCPU</Platforms>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>$(DefineConstants);STRONGNAMED</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Neo4j.Driver\Neo4j.Driver.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
        <None Update="appsettings.ci.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>
</Project>
