# pr:
#  branches:
#    include:
#      - 2.0

trigger:
  batch: 'true'
  branches:
    include:
      - azure-pipelines

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    group: teamcity
  steps:
    - task: UsePythonVersion@0
      displayName: 'Setup python'
      inputs:
        versionSpec: '3.x' 
        addToPath: true 
        architecture: 'x64'
    - script: python -m pip install --upgrade boltkit==1.2.0
      displayName: 'Install boltkit'
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: test
        projects: '**/Neo4j.Driver.Tests/*.csproj'
        testRunTitle: 'UnitTests'
    - pwsh: |
        echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_11_X64"
      displayName: 'Use Java 11'
    - task: DotNetCoreCLI@2
      displayName: 'Run integration tests with 4.0 server'
      inputs:
        command: test
        projects: '**/Neo4j.Driver.IntegrationTests/*.csproj'
        testRunTitle: 'IntegrationTests-4.0'
      env:
        NEOCTRLARGS: "-e 4.0"
        TEAMCITY_HOST: $(TEAMCITY_HOST)
        TEAMCITY_USER: $(TEAMCITY_USER)
        TEAMCITY_PASSWORD: $(TEAMCITY_PASSWORD)
    - pwsh: |
        echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_8_X64"
      displayName: 'Use Java 8'
    - task: DotNetCoreCLI@2
      displayName: 'Run integration tests with 3.5 server'
      inputs:
        command: test
        projects: '**/Neo4j.Driver.IntegrationTests/*.csproj'
        testRunTitle: 'IntegrationTests-3.5'
      env:
        NEOCTRLARGS: "-e 3.5"
        TEAMCITY_HOST: $(TEAMCITY_HOST)
        TEAMCITY_USER: $(TEAMCITY_USER)
        TEAMCITY_PASSWORD: $(TEAMCITY_PASSWORD)
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
