# disable CI builds
trigger: none

# Only trigger for PR's targeting 2.0
pr:
    branches:
        include:
            - 2.0
    autoCancel: 'true'

parameters:
    serverVersions: ['-e 3.5', '-e 4.0']
    imageNames: ['ubuntu-16.04', 'vs2017-win2016']

jobs:
    - job: 'Build'

      variables:
        group: teamcity
    
      strategy:
        matrix:
            ${{ each imageName in parameters.imageNames }}:
                ${{ each serverVersion in parameters.serverVersions }}:
                    imageName: ${{ imageName }}
                    serverVersion: ${{ serverVersion }}
    
      pool:
        imageName: $(imageName)
    
      steps:
    
      - task: UsePythonVersion@0
        displayName: 'Setup python'
        inputs:
           versionSpec: '3.x'
           addToPath: true
           architecture: 'x64'
    
      - script: python -m pip install --upgrade boltkit==1.2.0
        displayName: 'Install boltkit'
    
      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: restore
          projects: '**/*.csproj'
    
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: build
          projects: '**/*.csproj'
    
      - task: DotNetCoreCLI@2
        displayName: 'Run unit tests'
        inputs:
          command: test
          projects: '**/Neo4j.Driver.Tests/*.csproj'
          testRunTitle: 'UnitTests'
    
      - pwsh: |
            echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_11_X64"
        displayName: 'Use Java 11'
        condition: and(succeeded(), startsWith(variables['serverVersion'], '-e 4'))
    
      - pwsh: |
            echo "##vso[task.setvariable variable=JAVA_HOME]$env:JAVA_HOME_8_X64"
        displayName: 'Use Java 8'
        condition: and(succeeded(), startsWith(variables['serverVersion'], '-e 3'))
    
      - task: DotNetCoreCLI@2
        displayName: 'Run integration tests'
        inputs:
          command: test
          projects: '**/Neo4j.Driver.IntegrationTests/*.csproj'
          testRunTitle: 'IntegrationTests-4.0'
        env:
          NEOCTRLARGS: $(neoctrlargs)
          TEAMCITY_HOST: $(TEAMCITY_HOST)
          TEAMCITY_USER: $(TEAMCITY_USER)
          TEAMCITY_PASSWORD: $(TEAMCITY_PASSWORD)
