<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Neo4j.Driver.Bolt\Neo4j.Driver.Bolt.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="7.2.1" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
      <PackageReference Include="Moq" Version="4.20.72" />
      <PackageReference Include="Moq.AutoMock" Version="3.6.1" />
      <PackageReference Include="NUnit" Version="4.4.0" />
      <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="System.Linq.Async" Version="7.0.0" />
    </ItemGroup>

</Project>
