<Project>
    <PropertyGroup>
        <Copyright>Copyright 2002-2023</Copyright>
        <Version>6.3.0</Version>
        <AssemblyVersion>6.3.0.0</AssemblyVersion>
        <AssemblyFileVersion>6.3.0.0</AssemblyFileVersion>
        <FileVersion>6.3.0.0</FileVersion>
    </PropertyGroup>

    <PropertyGroup>
        <XunitVersion>2.4.1</XunitVersion>
        <MSTestVersion>16.1.1</MSTestVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <SignAssembly>true</SignAssembly>
        <DelaySign>false</DelaySign>
        <AssemblyOriginatorKeyFile>..\neo4j.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://github.com/neo4j/neo4j-dotnet-driver</PackageProjectUrl>
        <PackageIcon>Neo4j-icon-color.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\Neo4j-icon-color.png" Pack="true" PackagePath=""/>
    </ItemGroup>
</Project>
