!: BOLT 4.1
!: AUTO HELLO
!: AUTO RESET
!: AUTO PULL_ALL

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": {"address": "127.0.0.1:9001"}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [300, [{"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"], "role": "READ"},{"addresses": ["127.0.0.1:9001", "127.0.0.1:9002"], "role": "ROUTE"}]]
   SUCCESS {}