// Copyright (c) "Neo4j"
// Neo4j Sweden AB [https://neo4j.com]
// 
// Licensed under the Apache License, Version 2.0 (the "License").
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

using System;
using Neo4j.Driver.Internal.Encryption;

namespace Neo4j.Driver.Preview.Encryption;

/// <summary>
/// Factory methods for creating <see cref="IPropertyEncryptionProfile"/> instances. This class is
/// part of the Encryption Preview feature, and is subject to change or removal.
/// </summary>
public static class PropertyEncryptionProfile
{
    /// <summary>
    /// Creates an Envelope encryption profile: data encryption keys are generated by the driver, wrapped by
    /// <paramref name="keyEncapsulationService"/>, and persisted in <paramref name="keyRepository"/>. This
    /// method is part of the Encryption Preview feature, and is subject to change or removal.
    /// </summary>
    /// <param name="name">The name of the profile.</param>
    /// <param name="keyEncapsulationService">The service that wraps and unwraps data encryption keys.</param>
    /// <param name="keyRepository">The repository that stores and retrieves encapsulated data encryption keys.</param>
    /// <returns>The configured profile.</returns>
    /// <exception cref="ArgumentException"><paramref name="name"/> is <see langword="null"/>, empty, or whitespace.</exception>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="keyEncapsulationService"/> or <paramref name="keyRepository"/> is <see langword="null"/>.
    /// </exception>
    public static IPropertyEncryptionProfile Envelope(
        string name,
        IKeyEncapsulationService keyEncapsulationService,
        IEncapsulatedKeyRepository keyRepository)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentNullException.ThrowIfNull(keyEncapsulationService);
        ArgumentNullException.ThrowIfNull(keyRepository);

        return new EnvelopeEncryptionProfile(name, keyEncapsulationService, keyRepository);
    }
}
